//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainSIMS
{
    using System;
    using System.Collections.Generic;

    public partial class Product
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Orders = new HashSet<Order>();
        }

        public Product(int id, string productName, string category, string description, decimal price, int scu, int quantity, string location, string supplierName)
        {
            // TODO: Complete member initialization
            ProductId = id;
            ProductName = productName;
            Category = category;
            Description = description;
            Price = price;
            SCU = scu;
            Quantity = quantity;
            Location = location;
            SupplierName = supplierName;
        }

        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> SCU { get; set; }
        public int Quantity { get; set; }
        public string Location { get; set; }
        public string SupplierName { get; set; }

        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}