//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainSIMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        private int id;

        public Product(int id, int scu, string productName, decimal price, int quantity, string location, string category, string supplierName)
        {
            this.id = id;
            SCU = scu;
            ProductName = productName;
            Price = price;
            Quantity = quantity;
            Location = location;
            Category = category;
            SupplierName = supplierName;
        }

        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Category { get; set; }
        public string Descrition { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> SCU { get; set; }
        public int Quantity { get; set; }
        public string Location { get; set; }
        public string SupplierName { get; set; }
    }
}
