//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainSIMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
       // private int id;
  
        public User(int id, string userName, string password, string role)
        {
            // TODO: Complete member initialization
            UserId = id;
            Username = userName;
            Password = password;
            Role = role;
        }

        public User()
        { }
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    }
}
